sudo: required
dist: trusty

language: cpp
compiler:
    - g++

install:
    # get c++11 support
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - boost-latest
        packages:
            - gcc-4.9
            - g++-4.9

before_script:
    # setup environment
    - sudo -H sh ./script/installation/packages.sh
    - wget https://gflags.googlecode.com/files/libgflags0_2.0-1_amd64.deb
    - sudo dpkg -i libgflags0_2.0-1_amd64.deb
    - wget https://gflags.googlecode.com/files/libgflags-dev_2.0-1_amd64.deb
    - sudo dpkg -i libgflags-dev_2.0-1_amd64.deb

script:
    # first, run validator
    - python ./script/validators/validator.py
      # build
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make
    - make check CTEST_OUTPUT_ON_FAILURE=TRUE
